// <auto-generated />
using EF_Concepts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Concepts.Migrations
{
    [DbContext(typeof(ManagementContext))]
    [Migration("20220901084645_Mig2")]
    partial class Mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_Concepts.Course", b =>
                {
                    b.Property<int>("C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_Id"), 1L, 1);

                    b.Property<int>("C_Cost")
                        .HasColumnType("int");

                    b.Property<string>("C_Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("studentS_ID")
                        .HasColumnType("int");

                    b.HasKey("C_Id");

                    b.HasIndex("studentS_ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EF_Concepts.Student", b =>
                {
                    b.Property<int>("S_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_ID"), 1L, 1);

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("S_age")
                        .HasMaxLength(120)
                        .HasColumnType("int");

                    b.Property<int>("Sage_Phone")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("S_ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EF_Concepts.Course", b =>
                {
                    b.HasOne("EF_Concepts.Student", "student")
                        .WithMany()
                        .HasForeignKey("studentS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });
#pragma warning restore 612, 618
        }
    }
}
